import * as ANSI_COLOURS from '../dist/ansi-colours.mjs';

console.log(`${ANSI_COLOURS.BLACK}ANSI_COLOURS.BLACK${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.RED}ANSI_COLOURS.RED${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.GREEN}ANSI_COLOURS.GREEN${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.YELLOW}ANSI_COLOURS.YELLOW${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BLUE}ANSI_COLOURS.BLUE${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.MAGENTA}ANSI_COLOURS.MAGENTA${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.CYAN}ANSI_COLOURS.CYAN${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.WHITE}ANSI_COLOURS.WHITE${ANSI_COLOURS.RESET}`);

console.log(`${ANSI_COLOURS.B_BLACK}ANSI_COLOURS.B_BLACK${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.B_RED}ANSI_COLOURS.B_RED${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.B_GREEN}ANSI_COLOURS.B_GREEN${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.B_YELLOW}ANSI_COLOURS.B_YELLOW${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.B_BLUE}ANSI_COLOURS.B_BLUE${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.B_MAGENTA}ANSI_COLOURS.B_MAGENTA${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.B_CYAN}ANSI_COLOURS.B_CYAN${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.B_WHITE}ANSI_COLOURS.B_WHITE${ANSI_COLOURS.RESET}`);

console.log(`${ANSI_COLOURS.BG_BLACK}ANSI_COLOURS.BG_BLACK${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_RED}ANSI_COLOURS.BG_RED${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_GREEN}ANSI_COLOURS.BG_GREEN${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_YELLOW}ANSI_COLOURS.BG_YELLOW${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_BLUE}ANSI_COLOURS.BG_BLUE${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_MAGENTA}ANSI_COLOURS.BG_MAGENTA${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_CYAN}ANSI_COLOURS.BG_CYAN${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_WHITE}ANSI_COLOURS.BG_WHITE${ANSI_COLOURS.RESET}`);

console.log(`${ANSI_COLOURS.BG_B_BLACK}ANSI_COLOURS.BG_B_BLACK${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_B_RED}ANSI_COLOURS.BG_B_RED${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_B_GREEN}ANSI_COLOURS.BG_B_GREEN${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_B_YELLOW}ANSI_COLOURS.BG_B_YELLOW${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_B_BLUE}ANSI_COLOURS.BG_B_BLUE${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_B_MAGENTA}ANSI_COLOURS.BG_B_MAGENTA${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_B_CYAN}ANSI_COLOURS.BG_B_CYAN${ANSI_COLOURS.RESET}`);
console.log(`${ANSI_COLOURS.BG_B_WHITE}ANSI_COLOURS.BG_B_WHITE${ANSI_COLOURS.RESET}`);
